baseURL = "http://jcchen9416.github.io/"
languageCode = "zh-cn"		# "en-us"
title = "jc blog"

theme = "ananke"		# "ananke"
hasCJKLanguage = true

googleAnalytics = "UA-134660551-1"
disqusShortname = "jcchen9416-blog"
